version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: notes-mongodb
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - notes-network

  postgres:
    image: postgres:15
    container_name: notes-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: notes-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev
    networks:
      - notes-network

  minio:
    image: minio/minio:latest
    container_name: notes-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - notes-network

volumes:
  mongodb_data:
  postgres_data:
  minio_data:

networks:
  notes-network:
    driver: bridge 