version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: notes-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - notes-network

volumes:
  mongodb_data:

networks:
  notes-network:
    driver: bridge 